on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and test
    runs-on: windows-latest

    strategy:
      matrix:
        node: [ 16, 18, 20 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install dependencies    
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Start App
        run: npm start &
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.SERVICE_ID }}
          api_key: ${{ secrets.API_TOKEN }}
          wait_deploy: true       
    
